apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  mountOptions:
    - nfsvers=3
    - nolock
    - tcp
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: transmission
    volumeAttributes:
      server: 192.168.1.10
      share: /volume/d73ade95-0807-4799-aa9b-ad45cbc0d598/.srv/.unifi-drive/homelab/.data/transmission
