apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bitwarden
resources:
- configmap.yaml
- rbac.yaml
- service.yaml
- ingress.yaml
- secret.yaml
- vaultwarden-deployment.yaml
- pv.yaml
- pvc.yaml
