apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant
resources:
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - pdb.yaml
  - configmap.yaml
