apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config-pv
spec:
  capacity:
    storage: 768Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: homeassistant-config
    volumeAttributes:
      server: 192.168.1.10
      share: /volume/d73ade95-0807-4799-aa9b-ad45cbc0d598/.srv/.unifi-drive/nfs/.data/homeassistant/config
