apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: kube-system
  labels:
    app: cloudflared
spec:
  endpoints:
    - port: metrics
      interval: 1m
      scheme: http
      path: /metrics
  selector:
    matchLabels:
      app: cloudflared
  namespaceSelector:
    matchNames:
      - kube-system
