apiVersion: v1
kind: Service
metadata:
  labels:
    app: adguardhome
  name: adguardhome-http
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: adguardhome
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adguardhome
  name: adguardhome-admin
  annotations:
    "io.cilium/lb-ipam-sharing-key": "dns"
    "io.cilium/lb-ipam-ips": "192.168.1.241"
spec:
  type: LoadBalancer
  ports:
    - name: admin
      port: 3000
      protocol: TCP
      targetPort: admin
  selector:
    app: adguardhome
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adguardhome
  name: dns-over-tls
  annotations:
    "io.cilium/lb-ipam-sharing-key": "dns"
    "io.cilium/lb-ipam-ips": "192.168.1.241"
spec:
  type: LoadBalancer
  ports:
    - name: dns-over-tls
      port: 853
      protocol: TCP
      targetPort: dns-over-tls
    - name: dns-over-quic
      port: 853
      protocol: UDP
      targetPort: dns-over-quic-2
  selector:
    app: adguardhome
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adguardhome
  name: dns-tcp-udp
  annotations:
    "io.cilium/lb-ipam-sharing-key": "dns"
    "io.cilium/lb-ipam-ips": "192.168.1.241"
spec:
  type: LoadBalancer
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
  selector:
    app: adguardhome
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adguardhome
  name: dnscrypt
  annotations:
    "io.cilium/lb-ipam-sharing-key": "dns"
    "io.cilium/lb-ipam-ips": "192.168.1.241"
spec:
  type: LoadBalancer
  ports:
    - name: dnscrypt
      port: 5443
      protocol: TCP
      targetPort: dnscrypt
    - name: dnscrypt-udp
      port: 5443
      protocol: UDP
      targetPort: dnscrypt-udp
  selector:
    app: adguardhome
