apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.10
  share: /var/nfs/shared/homelab
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=3
  - nolock
  - tcp
  - hard
  - noatime
  - rsize=1048576
  - wsize=1048576
