---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/upgrade.cattle.io/plan_v1.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: kubernetes
  namespace: kube-system
spec:
  # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
  version: v1.35.0
  concurrency: 1
  postCompleteDelay: 30s
  exclusive: true
  serviceAccountName: system-upgrade-controller
  secrets:
    - name: system-upgrade-controller
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  tolerations:
    - {
        key: node-role.kubernetes.io/control-plane,
        effect: NoSchedule,
        operator: Exists,
      }
  upgrade:
    image: alpine:3.23
    command:
      - sh
      - -c
    args:
      - >-
        wget -q -O /usr/local/bin/talosctl https://github.com/siderolabs/talos/releases/download/${TALOS_VERSION}/talosctl-linux-amd64 &&
        chmod +x /usr/local/bin/talosctl &&
        export NODE_IP=${NODE_IP:-$(hostname -i)} &&
        cp /var/run/secrets/talos.dev/talosconfig /tmp/talosconfig &&
        talosctl
        --talosconfig=/tmp/talosconfig
        --nodes=$(NODE_IP)
        upgrade-k8s
        --to=$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)
    envs:
      - name: TALOS_VERSION
        # renovate: datasource=github-releases depName=siderolabs/talos
        value: v1.12.0
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
