---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/upgrade.cattle.io/plan_v1.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: kubernetes
  namespace: kube-system
spec:
  # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
  version: v1.35.0
  concurrency: 1
  postCompleteDelay: 30s
  exclusive: true
  serviceAccountName: system-upgrade-controller
  secrets:
    - name: system-upgrade-controller
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  tolerations:
    - {
        key: node-role.kubernetes.io/control-plane,
        effect: NoSchedule,
        operator: Exists,
      }
  upgrade:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    image: ghcr.io/siderolabs/talosctl:v1.11.6
    command:
      - sh
      - -c
    args:
      - >-
        cp /var/run/secrets/talos.dev/talosconfig /tmp/talosconfig &&
        talosctl
        --talosconfig=/tmp/talosconfig
        --nodes=$(SYSTEM_UPGRADE_NODE_NAME)
        upgrade-k8s
        --to=$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)
