apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: system-upgrade-controller
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: system-upgrade-controller
    template:
      engineVersion: v2
      data:
        talosconfig: "{{ .SYSTEM_UPGRADE_CONTROLLER_TALOS_SECRET }}"
  data:
    - secretKey: SYSTEM_UPGRADE_CONTROLLER_TALOS_SECRET
      remoteRef:
        key: SYSTEM_UPGRADE_CONTROLLER_TALOS_SECRET
