apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
#- letsencrypt-prod.yaml
- zerossl-prod.yaml
- secret.yaml
- wildcard-certificate.yaml
#- prometheus-rule.yaml
